const assert=require('node:assert/strict');
const ACL=require('./access-control.js');
const F=require('./access-test-fixtures.js');
const results=[];const test=(key,fn)=>{fn();results.push(key)};
let state=F.seed(),admin=state.users[0],worker=state.users[1],clientA=state.users[2],clientB=state.users[3];
test('catalog-7',()=>assert.equal(ACL.SECTIONS.length,7));
test('ceiling-exact',()=>assert.deepEqual(ACL.CEILINGS,{Admin:['section.dashboard','section.tools','section.team','section.users','section.suppliers','section.specs','section.orders'],Worker:['section.dashboard','section.tools','section.team','section.suppliers','section.specs'],Client:['section.dashboard','section.orders']}));
test('valid-222',()=>assert.equal(ACL.validateState(state).ok,true));
test('unknown-route',()=>assert.equal(ACL.authorizeRoute({state,user:admin,route:'future'}).reason,'route.unknown'));
test('unknown-action',()=>assert.equal(ACL.authorizeAction({state,user:admin,action:'future',phase:'execute',route:'home'}).reason,'action.unknown'));
test('unknown-phase',()=>assert.equal(ACL.authorizeAction({state,user:admin,action:'edit-user',phase:'future',route:'users',targetId:'worker'}).reason,'phase.unknown'));
test('missing-target',()=>assert.equal(ACL.authorizeAction({state,user:admin,action:'edit-user',phase:'open',route:'users'}).reason,'target.required'));
test('worker-project-scope',()=>{assert.equal(ACL.authorizeRoute({state,user:worker,route:'project',projectId:'p1'}).allowed,true);assert.equal(ACL.authorizeRoute({state,user:worker,route:'project',projectId:'p2'}).allowed,false)});
test('supplier-scopes',()=>{let list=ACL.selectSuppliersForActor(state,worker);assert.deepEqual(list.map(x=>[x.id,x.scope]),[['s-own','own'],['s-mixed','mixed']]);assert.equal(ACL.authorizeAction({state,user:worker,action:'edit-supplier',phase:'open',route:'suppliers',targetId:'s-own'}).allowed,true);assert.equal(ACL.authorizeAction({state,user:worker,action:'edit-supplier',phase:'open',route:'suppliers',targetId:'s-mixed'}).allowed,false)});
test('spec-scopes',()=>assert.deepEqual(ACL.selectSpecsForActor(state,worker).map(x=>x.id),['sp-own']));
test('client-isolation',()=>{assert.deepEqual(ACL.selectOrdersForActor(state,clientA).map(x=>x.id),['o1']);assert.deepEqual(ACL.selectOrdersForActor(state,clientB).map(x=>x.id),['o2']);assert.equal(ACL.canReadClientOrder(state,clientA,'o2'),false)});
test('visible-ignored',()=>{let changed=F.variant(s=>s.orders.forEach(o=>o.visible=true));assert.equal(ACL.canReadClientOrder(changed,changed.users[2],'o2'),false)});
test('contradiction-invalid',()=>{let bad=F.variant(s=>s.clientOrderAuthorizations[0].companyId='co2');assert.equal(ACL.validateState(bad).ok,false);assert.equal(ACL.canReadClientOrder(bad,bad.users[2],'o1'),false)});
test('dangling-invalid',()=>{let bad=F.variant(s=>s.projects.splice(0,1));assert.equal(ACL.validateState(bad).ok,false)});
test('duplicate-invalid',()=>{let bad=F.variant(s=>s.clientOrderAuthorizations.push({...s.clientOrderAuthorizations[0]}));assert.equal(ACL.validateState(bad).ok,false)});
test('no-admin-invalid',()=>{let bad=F.variant(s=>s.users=s.users.filter(x=>x.role!=='Admin'));assert.equal(ACL.validateState(bad).ok,false)});
test('migration-pure',()=>{let legacy=F.seed();delete legacy.schemaVersions;delete legacy.meta;let before=JSON.stringify(legacy),out=ACL.migrateState(legacy);assert.equal(JSON.stringify(legacy),before);assert.notEqual(out.state,legacy)});
test('migration-unknown-closed',()=>{let future=F.seed();future.schemaVersions.access=99;let out=ACL.migrateState(future);assert.equal(out.ok,false);assert.equal(out.errors[0],'schema.version')});
test('migration-empty-stays-empty',()=>{let empty=F.variant(s=>{s.projectMemberships=[];s.projectCompanies=[];s.supplierProjectLinks=[];s.clientProjectLinks=[];s.clientOrderAuthorizations=[]});let out=ACL.migrateState(empty);assert.equal(out.ok,true);assert.equal(out.state.projectMemberships.length,0)});
test('draft-monotonic',()=>{let d=ACL.createAccessDraft(worker,0),d1=ACL.reduceAccessDraft(d,{type:'confirm'}),d2=ACL.reduceAccessDraft(d1,{type:'grant',id:'section.specs',value:'disabled'});assert.equal(d1.confirmedRevision,0);assert.equal(d2.revision,1);assert.equal(d2.confirmedRevision,-1)});
test('all-projects-dynamic',()=>{let all=F.variant(s=>s.users[1].access.projectScope={mode:'all'});assert.deepEqual(ACL.selectProjectsForActor(all,all.users[1]).map(x=>x.id),['p1','p2'])});
test('draft-role-cancel',()=>{let d=ACL.createAccessDraft(worker,0),requested=ACL.reduceAccessDraft(d,{type:'request-role',role:'Client'}),cancelled=ACL.reduceAccessDraft(requested,{type:'cancel-role'});assert.equal(cancelled.role,'Worker');assert.equal(cancelled.revision,0)});
test('i18n-pairs',()=>Object.keys(ACL.I18N.es).forEach(key=>assert.ok(ACL.I18N.en[key])));
const report={suite:'access-control',pass:true,assertions:results};if(process.argv.includes('--report-json'))console.log(JSON.stringify(report));else console.log('access-control: all assertions passed');
