(function(root,factory){const api=factory(root.VAAKAccess,root.VAAKFixtures);if(typeof module==='object'&&module.exports)module.exports=factory(require('./access-control.js'),require('./access-test-fixtures.js'));else root.VAAKRuntime=api})(typeof globalThis!=='undefined'?globalThis:this,function(ACL,Fixtures){
  'use strict';
  const STORE='vaak-local-v8',LEGACY_STORE='vaak-preview-v7',SESSION='vaak-session-tab-v1',LEGACY_SESSION='vaak-session-v6',BOOTSTRAP='vaak-session-bootstrap-v1',copy=value=>value==null?value:JSON.parse(JSON.stringify(value)),freeze=value=>{if(value&&typeof value==='object'&&!Object.isFrozen(value)){Object.freeze(value);Object.values(value).forEach(freeze)}return value};
  function createRuntime(options={}){
    const storage=options.storage||localStorage,tabStorage=options.sessionStorage||(typeof sessionStorage!=='undefined'?sessionStorage:storage),clock=options.clock||(()=>Date.now()),tokens=new Map(),trace=[],present=options.present||(()=>{}),notify=options.notify||(()=>{});let route='home',selectedProjectId='p1',recovery=false,dispatcherCount=0;
    const readRaw=()=>storage.getItem(STORE),readSession=()=>{let actor=tabStorage.getItem(SESSION);if(actor)return actor;if(!tabStorage.getItem(BOOTSTRAP)){tabStorage.setItem(BOOTSTRAP,'legacy-copied');let legacy=storage.getItem(LEGACY_SESSION);if(legacy){tabStorage.setItem(SESSION,legacy);return legacy}}return null},writeStore=raw=>storage.setItem(STORE,raw);
    function prepareStore(){let raw=readRaw();if(raw==null){let source=storage.getItem(LEGACY_STORE);if(source==null)source=JSON.stringify(Fixtures.seed());let parsedSource;try{parsedSource=JSON.parse(source)}catch{return {ok:false,status:'recovery',reason:'json.invalid',raw:source}}let migrated=ACL.migrateState(parsedSource);if(!migrated.ok)return {ok:false,status:'recovery',reason:migrated.errors[0]||'state.invalid',raw:source};writeStore(JSON.stringify(migrated.state));raw=readRaw()}let parsed;try{parsed=JSON.parse(raw)}catch{return {ok:false,status:'recovery',reason:'json.invalid',raw}}let migration=ACL.migrateState(parsed);if(!migration.ok)return {ok:false,status:'recovery',reason:migration.errors[0]||'state.invalid',raw};if(migration.migrated){if(readRaw()!==raw)return prepareStore();let next=copy(migration.state);next.meta.storeRevision++;writeStore(JSON.stringify(next));raw=readRaw();parsed=JSON.parse(raw)}else parsed=migration.state;let validation=ACL.validateState(parsed);if(!validation.ok)return {ok:false,status:'recovery',reason:validation.errors[0],raw};return {ok:true,status:'ready',raw,state:freeze(copy(parsed))}}
    function loadFreshContext(){trace.push('read:store','read:session');let prepared=prepareStore();if(!prepared.ok){recovery=true;tokens.clear();tabStorage.removeItem(SESSION);return {...prepared,user:null}}recovery=false;let session=readSession(),user=prepared.state.users.find(x=>x.id===session&&x.active)||null;if(session&&!user)tabStorage.removeItem(SESSION);return {...prepared,user}}
    function refreshFromStorage(){tokens.clear();return loadFreshContext()}
    function operationToken(command,context,draft=null){let token=`op-${clock()}-${Math.random().toString(36).slice(2)}`,target=command.targetId||null,resourceRevision=target?JSON.stringify(context.state[({user:'users',project:'projects',supplier:'suppliers',spec:'specs',order:'orders',task:'tasks'}[command.resource?.type]||'users')]?.find(x=>x.id===target)||null):null;tokens.set(token,{actorId:context.user?.id||null,action:command.action,targetId:target,resource:copy(command.resource||null),route,openedStoreRevision:context.state?.meta?.storeRevision??-1,resourceRevision,draft,expires:clock()+900000,used:false});return token}
    function authorize(command,context){return ACL.authorizeAction({state:context.state,user:context.user,action:command.action,phase:command.phase,route,targetId:command.targetId,selectedProjectId,recovery,signedOut:!context.user&&!recovery})}
    function validateToken(command,context){let op=tokens.get(command.operationToken);if(!op||op.used||op.expires<clock())return {ok:false,reason:'token.invalid'};if(op.actorId!==context.user?.id||op.action!==command.action||op.targetId!==(command.targetId||null)||op.route!==route)return {ok:false,reason:'token.mismatch'};if(op.openedStoreRevision!==context.state.meta.storeRevision)return {ok:false,reason:'token.stale'};return {ok:true,op}}
    function commitState(command,reducer){let context=loadFreshContext();if(!context.ok)return {ok:false,reason:context.reason};let checked=validateToken(command,context);if(!checked.ok)return checked;let auth=authorize(command,context);if(!auth.allowed)return {ok:false,reason:auth.reason};let before=context.raw,next=copy(context.state);let reduced=reducer(next,checked.op);if(reduced===false)return {ok:false,reason:'reducer.denied'};next.meta.storeRevision++;let validation=ACL.validateState(next);if(!validation.ok)return {ok:false,reason:validation.errors[0]};if(readRaw()!==before)return {ok:false,reason:'store.stale'};writeStore(JSON.stringify(next));checked.op.used=true;tokens.delete(command.operationToken);let persisted=loadFreshContext();return persisted.ok?{ok:true,state:persisted.state,result:reduced}:persisted}
    const scopesFor=(state,userId)=>{let user=state.users.find(x=>x.id===userId);return {projectMode:user?.access?.projectScope?.mode||'selected',projectIds:state.projectMemberships.filter(x=>x.userId===userId).map(x=>x.projectId),clientProjectIds:state.clientProjectLinks.filter(x=>x.clientId===userId).map(x=>x.projectId),clientOrderIds:state.clientOrderAuthorizations.filter(x=>x.clientId===userId).map(x=>x.orderId)}};
    function applyUserScopes(state,userId,draft){
      state.projectMemberships=state.projectMemberships.filter(x=>x.userId!==userId);state.clientProjectLinks=state.clientProjectLinks.filter(x=>x.clientId!==userId);state.clientOrderAuthorizations=state.clientOrderAuthorizations.filter(x=>x.clientId!==userId);
      if(draft.role==='Worker'&&draft.projectMode!=='all')for(const projectId of draft.projectIds)state.projectMemberships.push({userId,projectId});
      if(draft.role==='Client'){
        let selected=draft.projectMode==='all'?state.projects.map(x=>x.id):draft.clientProjectIds;for(const projectId of selected){let company=state.projectCompanies.find(x=>x.projectId===projectId);if(!company)return false;state.clientProjectLinks.push({clientId:userId,companyId:company.companyId,projectId})}
        for(const orderId of draft.clientOrderIds){let order=state.orders.find(x=>x.id===orderId),link=order&&state.clientProjectLinks.find(x=>x.clientId===userId&&x.projectId===order.projectId);if(!order||!link)return false;state.clientOrderAuthorizations.push({clientId:userId,companyId:link.companyId,projectId:order.projectId,orderId})}
      }return true
    }
    const HANDLERS={
      'new-user':{open:(c,x)=>({kind:'user-editor',mode:'new',draft:ACL.createAccessDraft(null,x.state.meta.storeRevision)}),commit:(state,op,payload)=>{if(op.draft.confirmedRevision!==op.draft.revision)return false;let id=`u-${Date.now()}`,access={version:2,grants:copy(op.draft.grants),projectScope:{mode:op.draft.projectMode}};state.users.push({id,name:payload.name,email:payload.email,username:payload.username,password:payload.password,role:op.draft.role,active:true,access:op.draft.role==='Admin'?undefined:access});if(!applyUserScopes(state,id,op.draft))return false;return {id}}},
      'edit-user':{open:(c,x)=>{let target=x.state.users.find(u=>u.id===c.targetId);return {kind:'user-editor',mode:'edit',target:copy(target),draft:ACL.createAccessDraft(target,x.state.meta.storeRevision,scopesFor(x.state,c.targetId))}},commit:(state,op,payload)=>{let target=state.users.find(x=>x.id===op.targetId);if(!target)return false;Object.assign(target,{name:payload.name,email:payload.email,username:payload.username});return {id:target.id}}},
      'edit-access':{open:(c,x)=>{let target=x.state.users.find(u=>u.id===c.targetId);return {kind:'user-editor',mode:'access',accessOnly:true,target:copy(target),draft:ACL.createAccessDraft(target,x.state.meta.storeRevision,scopesFor(x.state,c.targetId))}},commit:(state,op)=>{if(op.draft.confirmedRevision!==op.draft.revision)return false;let target=state.users.find(x=>x.id===op.targetId);if(!target||target.role==='Admin')return false;target.access={version:2,grants:copy(op.draft.grants),projectScope:{mode:op.draft.projectMode}};if(!applyUserScopes(state,target.id,op.draft))return false;return {id:target.id}}},
      'toggle-user':{open:(c,x)=>({kind:'confirm-toggle',target:copy(x.state.users.find(u=>u.id===c.targetId))}),commit:(state,op)=>{let target=state.users.find(x=>x.id===op.targetId);if(!target||target.id===op.actorId)return false;target.active=!target.active;if(state.users.filter(x=>x.role==='Admin'&&x.active).length<1)return false;return true}},
      'new-supplier':{open:()=>({kind:'supplier-editor',mode:'new'}),commit:(state,op,p)=>{let id=`s-${Date.now()}`;state.suppliers.push({id,name:p.name,ruc:p.ruc,email:p.email,active:true});(p.projectIds||[]).forEach(projectId=>state.supplierProjectLinks.push({supplierId:id,projectId}));return {id}}},
      'edit-supplier':{open:(c,x)=>({kind:'supplier-editor',mode:'edit',target:copy(x.state.suppliers.find(s=>s.id===c.targetId))}),commit:(state,op,p)=>{let target=state.suppliers.find(x=>x.id===op.targetId);if(!target)return false;Object.assign(target,{name:p.name,ruc:p.ruc,email:p.email});return true}},
      'toggle-supplier':{open:(c,x)=>({kind:'confirm-supplier',target:copy(x.state.suppliers.find(s=>s.id===c.targetId))}),commit:(state,op)=>{let target=state.suppliers.find(x=>x.id===op.targetId);if(!target)return false;target.active=!target.active;return true}},
      'new-spec':{open:()=>({kind:'spec-editor'}),commit:(state,op,p)=>{state.specs.push({id:`sp-${Date.now()}`,projectId:p.projectId,name:p.name,category:p.category,color:p.color,cost:p.cost,image:p.image||''});return true},'async-commit':(state,op,p)=>{state.specs.push({id:`sp-${Date.now()}`,projectId:p.projectId,name:p.name,category:p.category,color:p.color,cost:p.cost,image:p.image||''});return true}},
      'new-order':{open:()=>({kind:'order-editor',items:[{}]}),commit:(state,op,p)=>{let next=Math.max(0,...state.orders.map(o=>Number((o.trackingNumber||'').match(/(\d+)$/)?.[1]||0)))+1,actor=state.users.find(u=>u.id===op.actorId);state.orders.push({...p,id:`o-${Date.now()}`,projectId:p.projectId,number:`PO-2026-${String(state.orders.length+1).padStart(3,'0')}`,trackingNumber:`TRK-2026-${String(next).padStart(5,'0')}`,trackingStatus:'Pickup',trackingUpdatedBy:{username:actor?.username||'',name:actor?.name||''},trackingUpdatedAt:new Date().toISOString()});return true}},
      'edit-order-tracking':{open:(c,x)=>({kind:'tracking-editor',target:copy(x.state.orders.find(o=>o.id===c.targetId))}),commit:(state,op,p)=>{let order=state.orders.find(o=>o.id===op.targetId),actor=state.users.find(u=>u.id===op.actorId);if(!order||!['Pickup','In transit','Arrived at client warehouse','Delivered'].includes(p.status))return false;if(!order.trackingNumber){let next=Math.max(0,...state.orders.map(o=>Number((o.trackingNumber||'').match(/(\d+)$/)?.[1]||0)))+1;order.trackingNumber=`TRK-2026-${String(next).padStart(5,'0')}`}order.trackingStatus=p.status;order.trackingUpdatedBy={username:actor?.username||'',name:actor?.name||''};order.trackingUpdatedAt=new Date().toISOString();return true}},
      'assign-team-objective':{open:(c,x)=>({kind:'team-objective-editor',mode:'new',users:copy(x.state.users.filter(u=>u.active&&['Worker','Admin'].includes(u.role)))}),commit:(state,op,p)=>{if(!state.users.some(u=>u.id===p.assignee&&u.active))return false;state.tasks.push({id:`t-${Date.now()}`,title:p.title,description:p.description||'',assignee:p.assignee,status:'Pending',progress:0,period:p.period||'Weekly',reference:p.reference||'',due:p.due||''});return true}},
      'edit-team-objective':{open:(c,x)=>({kind:'team-objective-editor',mode:'edit',target:copy(x.state.tasks.find(t=>t.id===c.targetId)),users:copy(x.state.users.filter(u=>u.active&&['Worker','Admin'].includes(u.role)))}),commit:(state,op,p)=>{let task=state.tasks.find(t=>t.id===op.targetId);if(!task||!state.users.some(u=>u.id===p.assignee&&u.active))return false;Object.assign(task,{title:p.title,description:p.description||'',assignee:p.assignee,period:p.period||'Weekly',reference:p.reference||'',due:p.due||'',status:p.status||task.status,progress:Number(p.progress??task.progress)});return true}},
      'delete-team-objective':{open:(c,x)=>({kind:'confirm-task-delete',target:copy(x.state.tasks.find(t=>t.id===c.targetId))}),commit:(state,op)=>{let size=state.tasks.length;state.tasks=state.tasks.filter(t=>t.id!==op.targetId);return state.tasks.length<size}},
      task:{open:(c,x)=>({kind:'task-status',target:copy(x.state.tasks.find(t=>t.id===c.targetId))}),commit:(state,op,p)=>{let task=state.tasks.find(x=>x.id===op.targetId);if(!task)return false;task.status=p.status;task.progress=Number(p.progress||0);return true}},
      'advance-team-objective':{open:(c,x)=>({kind:'task-status',target:copy(x.state.tasks.find(t=>t.id===c.targetId))}),commit:(state,op,p)=>{let task=state.tasks.find(x=>x.id===op.targetId);if(!task)return false;task.status=p.status;task.progress=Number(p.progress||0);return true}},
      'new-project':{open:()=>({kind:'project-editor'}),'async-commit':(state,op,p)=>{state.projects.push({id:`p-${Date.now()}`,code:`PRJ-${String(state.projects.length+41).padStart(3,'0')}`,name:p.name,legal:p.name,fiscal:p.address,city:p.city,country:p.country,contact:p.contact,phone:p.phone,cover:p.cover,gallery:[],team:[],rooms:'—',residences:'—',areas:'—'});return true}},
      'edit-project-card':{open:(c,x)=>({kind:'project-card-editor',section:c.payload?.section||'general',target:copy(x.state.projects.find(p=>p.id===c.targetId))}),commit:(state,op,p)=>{let project=state.projects.find(p=>p.id===op.targetId);if(!project)return false;if(op.section==='areas')Object.assign(project,{rooms:p.rooms,residences:p.residences,areas:p.areas});else Object.assign(project,{legal:p.legal,fiscal:p.fiscal,warehouse:p.warehouse,city:p.city,country:p.country});return true}},
      'edit-profile-photo':{open:(c,x)=>({kind:'profile-photo-editor',target:copy(x.state.users.find(u=>u.id===x.user.id))}),'async-commit':(state,op,p)=>{let user=state.users.find(u=>u.id===op.actorId);if(!user||!p.photo)return false;user.profilePhoto=p.photo;return true}},
      'remove-team-member':{open:(c,x)=>({kind:'confirm-team-member-remove',target:copy(x.state.projects.find(p=>p.id===c.targetId)),index:Number(c.payload?.index)}),commit:(state,op,p)=>{let project=state.projects.find(x=>x.id===op.targetId),index=Number(p.index),defaults=[{name:'María Fernanda López',role:'Gerente de Proyecto',phone:'+51 987 123 456'},{name:'Jorge Ramírez',role:'Administrador de Obra',phone:'+51 956 321 780'},{name:'Lucía Torres',role:'Coordinadora de Compras',phone:'+51 944 876 210'}];if(!project||!Number.isInteger(index)||index<0)return false;if(!project.team?.length)project.team=defaults;if(index>=project.team.length)return false;project.team.splice(index,1);return true}},
      'edit-banner':{open:(c,x)=>({kind:'banner-editor',target:copy(x.state.projects.find(p=>p.id===c.targetId))}),'async-commit':(state,op,p)=>{let project=state.projects.find(x=>x.id===op.targetId),images=(p.images||[]).filter(Boolean).slice(0,5);if(!project||!images.length)return false;project.cover=images[0];project.gallery=images.slice(1);return true}},
      'new-invoice':{open:(c,x)=>({kind:'invoice-editor',target:copy(x.state.projects.find(p=>p.id===c.targetId))}),commit:(state,op,p)=>{let project=state.projects.find(p=>p.id===op.targetId),all=state.projects.flatMap(p=>p.invoices||[]),next=all.length+1;if(!project)return false;(project.invoices||=[]).push({...p,id:`inv-${Date.now()}`,number:`PR-2026-${String(next).padStart(5,'0')}`,issuedBy:state.users.find(u=>u.id===op.actorId)?.name||'',createdAt:new Date().toISOString()});return true}},
      'preview-invoice':{open:(c,x)=>{let project=x.state.projects.find(p=>p.id===c.targetId),invoice=(project?.invoices||[]).find(i=>i.id===c.payload?.invoiceId);return {kind:'invoice-preview',target:copy(project),invoice:copy(invoice)}}},'delete-invoice':{open:(c,x)=>{let project=x.state.projects.find(p=>p.id===c.targetId),invoice=(project?.invoices||[]).find(i=>i.id===c.payload?.invoiceId);return {kind:'confirm-invoice-delete',target:copy(project),invoice:copy(invoice)}},commit:(state,op,p)=>{let project=state.projects.find(item=>item.id===op.targetId),before=project?.invoices?.length||0;if(!project)return false;project.invoices=(project.invoices||[]).filter(invoice=>invoice.id!==p.invoiceId);return project.invoices.length<before}},
      'preview-order':{open:(c,x)=>({kind:'order-preview',target:copy(x.state.orders.find(o=>o.id===c.targetId))})},'download-order':{open:(c,x)=>({kind:'order-preview',target:copy(x.state.orders.find(o=>o.id===c.targetId))})},'delete-order':{open:(c,x)=>({kind:'confirm-order-delete',target:copy(x.state.orders.find(o=>o.id===c.targetId))}),commit:(state,op)=>{let before=state.orders.length;state.orders=state.orders.filter(x=>x.id!==op.targetId);state.clientOrderAuthorizations=state.clientOrderAuthorizations.filter(x=>x.orderId!==op.targetId);return state.orders.length<before}},'preview-spec':{open:(c,x)=>({kind:'spec-preview',target:copy(x.state.specs.find(o=>o.id===c.targetId))})},'view-image':{open:(c,x)=>({kind:'image-preview',target:copy(x.state.projects.find(o=>o.id===c.targetId))})},
      'reset-demo':{open:()=>({kind:'reset-confirm'}),commit:()=>true}
    };
    Object.freeze(HANDLERS);
    function mutateDraft(command,context){let op=tokens.get(command.operationToken);if(!op||op.used||op.expires<clock()||op.actorId!==context.user?.id||op.route!==route||!['new-user','edit-user','edit-access'].includes(op.action))return {ok:false,reason:'token.invalid'};let typeMap={'confirm-access-review':'confirm','request-role-change':'request-role','confirm-role-change':'confirm-role','cancel-role-change':'cancel-role','request-tools-removal':'request-tools-remove','confirm-tools-removal':'confirm-tools-remove','cancel-tools-removal':'cancel-tools-remove'},event=command.payload?.changeEvent||{type:typeMap[command.action],...(command.payload||{})};op.draft=ACL.reduceAccessDraft(op.draft,event);return {ok:true,draft:op.draft}}
    function dispatchAction(command){dispatcherCount++;trace.push(`dispatch:${command.action}:${command.phase}`);let context=loadFreshContext();if(['confirm-access-review','request-role-change','confirm-role-change','cancel-role-change','request-tools-removal','confirm-tools-removal','cancel-tools-removal'].includes(command.action))return mutateDraft(command,context);let auth=authorize(command,context);if(!auth.allowed){notify(ACL.t(options.language?.()||'es','denied'));return {ok:false,reason:auth.reason}}let handler=HANDLERS[command.action];
      if(command.phase==='open'){let descriptor=handler?.open?handler.open(command,context):{kind:'notice',action:command.action};let token=operationToken(command,context,descriptor.draft||null);descriptor={...descriptor,operationToken:token};present(copy(descriptor));return {ok:true,descriptor}}
      if(['commit','async-commit'].includes(command.phase)){if(command.action==='reset-demo'){let checked=validateToken(command,context);if(!checked.ok)return checked;writeStore(JSON.stringify(Fixtures.seed()));tabStorage.removeItem(SESSION);tabStorage.setItem(BOOTSTRAP,'reset');tokens.clear();return {ok:true,reset:true}}let reducer=handler?.[command.phase];if(!reducer)return {ok:false,reason:'handler.missing'};return commitState(command,(state,op)=>reducer(state,op,copy(command.payload||{})))}
      if(command.action==='logout'){tabStorage.removeItem(SESSION);tabStorage.setItem(BOOTSTRAP,'logout');tokens.clear();return {ok:true}}if(command.action==='close'){if(command.operationToken)tokens.delete(command.operationToken);return {ok:true}}return {ok:true,action:command.action}}
    function navigateTo(nextRoute,projectId){let context=loadFreshContext();let decision=ACL.authorizeRoute({state:context.state,user:context.user,route:nextRoute,projectId});if(!decision.allowed)return {ok:false,reason:decision.reason};route=nextRoute;if(projectId)selectedProjectId=projectId;return {ok:true}}
    function renderCurrentRoute(){let context=loadFreshContext();if(!context.ok)return {status:'recovery',reason:context.reason};if(!context.user)return {status:'signed_out'};let allowed=ACL.authorizeRoute({state:context.state,user:context.user,route,projectId:selectedProjectId});if(!allowed.allowed){let candidates=['home','tools','team','users','suppliers','specs','orders'],fallback=candidates.find(r=>ACL.authorizeRoute({state:context.state,user:context.user,route:r}).allowed);if(!fallback){tabStorage.removeItem(SESSION);tabStorage.setItem(BOOTSTRAP,'revoked');return {status:'signed_out'}}route=fallback}return {status:'ready',state:context.state,user:context.user,route,selectedProjectId}}
    const openAuthorizedOperation=command=>dispatchAction({...command,phase:'open'});
    return freeze({STORE,SESSION,LEGACY_STORE,LEGACY_SESSION,dispatchAction,navigateTo,renderCurrentRoute,openAuthorizedOperation,refreshFromStorage,loadFreshContext,signIn:id=>{tabStorage.setItem(SESSION,id);tabStorage.setItem(BOOTSTRAP,'login');tokens.clear()},getTrace:()=>trace.slice(),getDispatcherCount:()=>dispatcherCount,setRoute:(value,id)=>{route=value;if(id)selectedProjectId=id}})
  }
  return freeze({createRuntime,STORE,SESSION,LEGACY_STORE,LEGACY_SESSION});
});
