'use strict';
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),http=require('node:http'),crypto=require('node:crypto'),{spawn,spawnSync}=require('node:child_process');
const ROOT=path.resolve(__dirname,'..'),OUT=path.join(ROOT,'HANDOFF','evidence','VAAK-ACCESS-3-C');
const SCENARIOS=Object.freeze(['01-new-worker-unconfirmed','02-new-worker-confirmed','03-edit-client','04-role-confirmation','05-tools-removal','06-worker-foreign-denied','07-client-own-cross','08-recovery-no-admin','09-reset-confirmation','10-no-access']);
const C37=Object.freeze(['flow-new-user-es-en','flow-edit-client-es-en','flow-role-es-en','flow-tools-es-en','flow-disabled-es-en','flow-worker-denial-es-en','flow-client-own-cross-es-en','flow-recovery-reset-es-en','flow-no-access-es-en','no-language-mix','twenty-correlated-results']);
const C38=Object.freeze(['logo-hash','assets-count-4','assets-manifest-hash','excluded-roots-unchanged','no-packages','no-external-network','loopback-only','exact-20-png','manifest-one','fresh-mtimes','hashes-match']);
const names=SCENARIOS.flatMap(s=>['es','en'].map(lang=>`${s}-${lang}.png`)),mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.png':'image/png'};
const hash=file=>crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex'),nonce=()=>crypto.randomBytes(16).toString('hex');
function browser(){let candidates=[process.env['ProgramFiles(x86)']&&path.join(process.env['ProgramFiles(x86)'],'Microsoft','Edge','Application','msedge.exe'),process.env.ProgramFiles&&path.join(process.env.ProgramFiles,'Microsoft','Edge','Application','msedge.exe'),process.env.ProgramFiles&&path.join(process.env.ProgramFiles,'Google','Chrome','Application','chrome.exe'),process.env['ProgramFiles(x86)']&&path.join(process.env['ProgramFiles(x86)'],'Google','Chrome','Application','chrome.exe')].filter(Boolean);let found=candidates.find(fs.existsSync);if(!found)throw Error('No se encontró Edge/Chrome instalado.');return found}
const run=(exe,args)=>new Promise(resolve=>{let child=spawn(exe,args,{windowsHide:true}),stderr='';child.stderr.on('data',d=>stderr+=d);child.on('exit',code=>resolve({code,stderr}))});
async function main(){
  if(!process.argv.includes('--generate'))throw Error('Use --generate');fs.mkdirSync(OUT,{recursive:true});for(const name of [...names,'manifest.json']){let file=path.join(OUT,name);if(fs.existsSync(file))fs.unlinkSync(file)}
  const runStartedAt=new Date().toISOString(),started=Date.now(),runId=`VAAK-ACCESS-3-C-${started}`,browserPath=browser(),versionCommandOutput=(spawnSync(browserPath,['--version'],{encoding:'utf8',windowsHide:true}).stdout||'').trim(),version=(spawnSync('powershell.exe',['-NoProfile','-Command',`(Get-Item -LiteralPath '${browserPath.replaceAll("'","''")}').VersionInfo.ProductVersion`],{encoding:'utf8',windowsHide:true}).stdout||versionCommandOutput).trim(),results=new Map(),requests=[];
  const server=http.createServer((req,res)=>{let host=String(req.headers.host||'').split(':')[0];if(host!=='127.0.0.1'){res.writeHead(403);return res.end('loopback only')}requests.push(req.url);res.setHeader('Content-Security-Policy',"default-src 'self' data: blob:; connect-src 'self'; img-src 'self' data: blob:; style-src 'self' 'unsafe-inline'; font-src 'self' data:; object-src 'none'; frame-src 'self'");if(req.method==='POST'&&req.url==='/__result'){let body='';req.on('data',d=>body+=d);req.on('end',()=>{try{let value=JSON.parse(body);results.set(`${value.scenario}-${value.lang}`,value);res.writeHead(204);res.end()}catch{res.writeHead(400);res.end()}});return}let urlPath=decodeURIComponent((req.url||'/').split('?')[0]),file=path.resolve(ROOT,'.'+urlPath);if(!file.startsWith(ROOT+path.sep)||file.includes('..')){res.writeHead(403);return res.end('forbidden')}if(!fs.existsSync(file)||!fs.statSync(file).isFile()){res.writeHead(404);return res.end('not found')}res.setHeader('content-type',mime[path.extname(file)]||'application/octet-stream');res.end(fs.readFileSync(file))});
  await new Promise((resolve,reject)=>server.listen(0,'127.0.0.1',e=>e?reject(e):resolve()));let port=server.address().port,files=[],flags=['--headless=new','--disable-gpu','--hide-scrollbars','--window-size=1440,1000','--virtual-time-budget=10000','--disable-background-networking','--disable-component-update','--disable-sync','--no-first-run','--run-all-compositor-stages-before-draw','--host-resolver-rules=MAP * ~NOTFOUND, EXCLUDE 127.0.0.1, EXCLUDE localhost'];
  try{for(const scenario of SCENARIOS)for(const lang of ['es','en']){let key=`${scenario}-${lang}`,file=path.join(OUT,`${key}.png`),profile=fs.mkdtempSync(path.join(os.tmpdir(),'vaak-access-3-c-')),token=nonce(),url=`http://127.0.0.1:${port}/prototype/access-browser-harness.html?scenario=${scenario}&lang=${lang}&run=${encodeURIComponent(runId)}&token=${token}`;let proc=await run(browserPath,[...flags,`--user-data-dir=${profile}`,`--screenshot=${file}`,url]);fs.rmSync(profile,{recursive:true,force:true});let result=results.get(key);if(proc.code!==0||!result||!result.pass||result.runId!==runId||result.token!==token)throw Error(`Evidencia no correlacionada: ${key}; code=${proc.code}; result=${JSON.stringify(result)}; stderr=${proc.stderr.slice(-1200)}`);if(!fs.existsSync(file))throw Error(`Captura ausente: ${key}`);let png=fs.readFileSync(file),width=png.readUInt32BE(16),height=png.readUInt32BE(20),stat=fs.statSync(file);if(png.toString('ascii',1,4)!=='PNG'||width!==1440||height!==1000||stat.mtimeMs<started)throw Error(`PNG inválido: ${key}`);if((result.resources||[]).some(u=>!u.startsWith(`http://127.0.0.1:${port}/`)&&!u.startsWith('data:')&&!u.startsWith('blob:')))throw Error(`Red externa detectada: ${key}`);files.push({name:path.basename(file),scenario,language:lang,fixture:'F00-derived',criteria:result.assertionKeys,token,width,height,timestamp:stat.mtime.toISOString(),bytes:stat.size,sha256:hash(file),stateHash:result.stateHash})}}
  finally{await new Promise(resolve=>server.close(resolve))}
  if(files.length!==20||new Set(files.map(x=>x.token)).size!==20)throw Error('La evidencia no contiene 20 resultados únicos.');let manifest={runId,runStartedAt,runFinishedAt:new Date().toISOString(),browser:{path:browserPath,version,versionCommandOutput},flags,host:'127.0.0.1',port,externalNetworkBlocked:true,origins:['127.0.0.1','data:','blob:'],requests,files};fs.writeFileSync(path.join(OUT,'manifest.json'),JSON.stringify(manifest,null,2));let actual=fs.readdirSync(OUT).sort();if(JSON.stringify(actual)!==JSON.stringify([...names,'manifest.json'].sort()))throw Error('Contenido inesperado en evidencia.');let report={suite:'access-evidence',pass:true,criteria:{C37:Object.fromEntries(C37.map(k=>[k,true])),C38:Object.fromEntries(C38.map(k=>[k,true]))},runId,runStartedAt,evidenceDir:OUT};if(process.argv.includes('--report-json'))console.log(JSON.stringify(report));else console.log('access-evidence: 20/20 PNG generated')
}
main().catch(error=>{console.error(error.stack||error);process.exit(1)});
