const assert=require('node:assert/strict');
const {createRuntime,STORE,SESSION}=require('./access-runtime.js');
const F=require('./access-test-fixtures.js');
class Storage{constructor(seed=F.seed(),session='admin'){this.map=new Map([[STORE,JSON.stringify(seed)],[SESSION,session]]);this.reads=[];this.writes=[]}getItem(k){this.reads.push(k);return this.map.has(k)?this.map.get(k):null}setItem(k,v){this.writes.push(k);this.map.set(k,v)}removeItem(k){this.map.delete(k)}}
const assertions=[],test=(key,fn)=>{fn();assertions.push(key)};
test('fresh-read',()=>{let s=new Storage,r=createRuntime({storage:s});r.renderCurrentRoute();assert.ok(s.reads.includes(STORE));assert.ok(s.reads.includes(SESSION))});
test('open-confirm-commit-user',()=>{let s=new Storage,r=createRuntime({storage:s});r.setRoute('users');let opened=r.dispatchAction({action:'new-user',phase:'open'});assert.equal(opened.ok,true);let token=opened.descriptor.operationToken;let confirmed=r.dispatchAction({action:'confirm-access-review',phase:'execute',operationToken:token});assert.equal(confirmed.draft.confirmedRevision,0);let committed=r.dispatchAction({action:'new-user',phase:'commit',operationToken:token,payload:{name:'Test User',email:'test@example.test',username:'test.user',password:'Demo123!'}});assert.equal(committed.ok,true);assert.equal(JSON.parse(s.getItem(STORE)).users.filter(x=>x.username==='test.user').length,1);assert.equal(r.dispatchAction({action:'new-user',phase:'commit',operationToken:token,payload:{}}).ok,false)});
test('stale-commit-denied',()=>{let s=new Storage,r=createRuntime({storage:s});r.setRoute('users');let opened=r.dispatchAction({action:'edit-user',phase:'open',targetId:'worker',resource:{type:'user',id:'worker'}}),state=JSON.parse(s.getItem(STORE));state.meta.storeRevision++;state.users[1].active=false;s.setItem(STORE,JSON.stringify(state));let result=r.dispatchAction({action:'edit-user',phase:'commit',targetId:'worker',resource:{type:'user',id:'worker'},operationToken:opened.descriptor.operationToken,payload:{}});assert.equal(result.ok,false);assert.equal(JSON.parse(s.getItem(STORE)).users[1].active,false)});
test('shared-session',()=>{let s=new Storage,r1=createRuntime({storage:s}),r2=createRuntime({storage:s});assert.equal(r1.renderCurrentRoute().user.id,'admin');s.setItem(SESSION,'worker');r1.refreshFromStorage();r2.refreshFromStorage();assert.equal(r1.renderCurrentRoute().user.id,'worker');assert.equal(r2.renderCurrentRoute().user.id,'worker')});
test('recovery-invalid-json',()=>{let s=new Storage();s.setItem(STORE,'{bad');let r=createRuntime({storage:s});assert.equal(r.renderCurrentRoute().status,'recovery');assert.equal(s.getItem(SESSION),null)});
test('dispatcher-counter',()=>{let s=new Storage,r=createRuntime({storage:s});r.setRoute('users');r.dispatchAction({action:'new-user',phase:'open'});assert.equal(r.getDispatcherCount(),1)});
const report={suite:'access-runtime',pass:true,assertions};if(process.argv.includes('--report-json'))console.log(JSON.stringify(report));else console.log('access-runtime: all assertions passed');
