(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.VAAKAccess=api})(typeof globalThis!=='undefined'?globalThis:this,function(){
  'use strict';
  const clone=value=>value==null?value:JSON.parse(JSON.stringify(value));
  const freeze=value=>{if(value&&typeof value==='object'&&!Object.isFrozen(value)){Object.freeze(value);Object.values(value).forEach(freeze)}return value};
  const decision=(allowed,reason)=>freeze({allowed,reason});
  const VERSION=freeze({access:2,relations:2,resources:2});
  const SECTIONS=freeze([
    {id:'section.dashboard',route:'home',roles:['Admin','Worker','Client']},{id:'section.tools',route:'tools',roles:['Admin','Worker']},
    {id:'section.team',route:'team',roles:['Admin','Worker']},{id:'section.users',route:'users',roles:['Admin']},
    {id:'section.suppliers',route:'suppliers',roles:['Admin','Worker']},{id:'section.orders',route:'orders',roles:['Client']},{id:'section.tracking',route:'tracking',roles:['Client']},
    {id:'section.specs',route:'specs',roles:['Admin','Worker']}
  ]);
  const ROUTES=freeze(Object.fromEntries(SECTIONS.map(x=>[x.route,x.id])));
  const CEILINGS=freeze({Admin:['section.dashboard','section.tools','section.team','section.users','section.suppliers','section.specs','section.orders'],Worker:['section.dashboard','section.tools','section.team','section.suppliers','section.specs'],Client:['section.dashboard','section.orders','section.tracking']});
  const LEGACY_DEFAULTS=freeze({Worker:['section.dashboard','section.tools','section.team','section.suppliers','section.specs'],Client:['section.dashboard','section.orders','section.tracking']});
  const rows={
    eye:['execute','signed_out',null,'login','forbidden',null,'system','ui'],close:['execute','*',null,'*','optional',null,'system','ui'],logout:['execute','Admin|Worker|Client',null,'*','forbidden',null,'system','ui'],
    'reset-demo':['open|commit','recovery',null,'recovery','forbidden',null,'recovery','write'],'advanced-team-filters':['execute','Admin|Worker','section.team','team','forbidden',null,'section','ui'],
    'assign-team-objective':['open|commit','Admin','section.team','team','forbidden',null,'admin','write'],'edit-team-objective':['open|commit','Admin','section.team','team','required','task','admin','write'],'delete-team-objective':['open|commit','Admin','section.team','team','required','task','admin','write'],
    task:['open|commit','Worker','section.team','team','required','task','own-task','write'],
    'new-user':['open|commit','Admin','section.users','users','forbidden',null,'admin','write'],'edit-user':['open|commit','Admin','section.users','users','required','user','admin','write'],'edit-access':['open|commit','Admin','section.users','users','required','user','admin','write'],'toggle-user':['open|commit','Admin','section.users','users','required','user','admin','write'],
    'confirm-access-review':['execute','Admin','section.users','users','optional',null,'draft','ui'],'request-role-change':['execute','Admin','section.users','users','optional',null,'draft','ui'],'confirm-role-change':['execute','Admin','section.users','users','optional',null,'draft','ui'],'cancel-role-change':['execute','Admin','section.users','users','optional',null,'draft','ui'],
    'request-tools-removal':['execute','Admin','section.users','users','optional',null,'draft','ui'],'confirm-tools-removal':['execute','Admin','section.users','users','optional',null,'draft','ui'],'cancel-tools-removal':['execute','Admin','section.users','users','optional',null,'draft','ui'],
    'new-project':['open|async-commit','Admin','section.dashboard','home','forbidden',null,'admin','write'],'edit-profile-photo':['open|async-commit','Admin|Worker|Client',null,'*','forbidden',null,'self','write'],'banner-next':['execute','Admin|Worker','section.dashboard','project','required','project','project-read','ui'],'banner-prev':['execute','Admin|Worker','section.dashboard','project','required','project','project-read','ui'],'view-image':['open','Admin|Worker','section.dashboard','project','required','project','project-read','read'],
    'edit-project-card':['open|commit','Admin','section.dashboard','project','required','project','project-write','write'],'add-team-member':['open|commit','Admin','section.dashboard','project','required','project','project-write','write'],'remove-team-member':['open|commit','Admin','section.dashboard','project','required','project','project-write','write'],'edit-banner':['open|async-commit','Admin','section.dashboard','project','required','project','project-write','write'],
    'new-supplier':['open|commit','Admin|Worker','section.suppliers','suppliers','forbidden',null,'project-write','write'],'edit-supplier':['open|commit','Admin|Worker','section.suppliers','suppliers','required','supplier','supplier-own','write'],'toggle-supplier':['open|commit','Admin|Worker','section.suppliers','suppliers','required','supplier','supplier-own','write'],'delete-supplier':['open|commit','Admin|Worker','section.suppliers','suppliers','required','supplier','supplier-own','write'],
    'new-spec':['open|commit|async-commit','Admin|Worker','section.specs','specs','forbidden',null,'project-write','write'],'edit-spec':['open|commit','Admin|Worker','section.specs','specs','required','spec','spec-own','write'],'preview-spec':['open','Admin|Worker','section.specs','specs','required','spec','spec-own','read'],
    'new-order':['open|commit','Admin|Worker','section.dashboard','project','forbidden',null,'project-write','write'],'po-preview-draft':['execute','Admin|Worker','section.dashboard','project','forbidden',null,'project-write','ui'],'delete-invoice':['open|commit','Admin|Worker','section.dashboard','project','required','project','project-write','write'],'add-item':['execute','Admin|Worker','section.dashboard','project','forbidden',null,'project-write','ui'],'remove-item':['execute','Admin|Worker','section.dashboard','project','optional',null,'project-write','ui'],
    'preview-order':['open','Admin|Client','section.orders','orders|home','required','order','client-order','read'],'download-order':['open','Admin','section.orders','orders','required','order','admin','read'],'delete-order':['open|commit','Admin|Worker','section.dashboard','project|orders','required','order','order-project-write','write'],'edit-order-tracking':['open|commit','Admin|Worker','section.dashboard','project','required','order','order-project-write','write'],'add-warehouse':['execute','Admin|Worker','section.dashboard','project','forbidden',null,'project-write','ui'],'new-invoice':['open|commit','Admin|Worker','section.dashboard','project','required','project','project-write','write'],'preview-invoice':['open','Admin|Worker','section.dashboard','project','required','project','project-read','read']
  };
  // The retired standalone image viewer is superseded by the banner gallery editor.
  delete rows['advanced-team-filters'];
  delete rows['view-image'];
  const denied=['new-task','edit-task','gallery','set-banner-cover','remove-banner-image','delete-viewed-image'];
  denied.forEach(name=>rows[name]=['','','','','forbidden',null,'deny','ui']);
  const ACTION_POLICY=freeze(Object.fromEntries(Object.entries(rows).map(([name,v])=>[name,{phases:v[0]?v[0].split('|'):[],roles:v[1]==='*'?['Admin','Worker','Client','signed_out','recovery']:v[1]?v[1].split('|'):[],permission:v[2],routes:v[3]==='*'?['*']:v[3]?v[3].split('|'):[],target:v[4],resolver:v[5],scope:v[6],effect:v[7]}])));
  const RESOLVERS=freeze({user:'users',project:'projects',supplier:'suppliers',spec:'specs',order:'orders',task:'tasks'});
  const I18N=freeze({es:{denied:'No tienes autorización para realizar esta acción.',stale:'Tus permisos o los datos cambiaron. Vuelve a abrir el formulario.',invalid:'El estado local es inválido.',noAccess:'Sin accesos habilitados',recovery:'Recuperación de la demo',review:'He revisado y confirmo estos accesos.',save:'Guardar cambios',cancel:'Cancelar',signOut:'Cerrar sesión'},en:{denied:'You are not authorized to perform this action.',stale:'Your access or the data changed. Reopen the form.',invalid:'The local state is invalid.',noAccess:'No enabled access',recovery:'Demo recovery',review:'I reviewed and confirm these access settings.',save:'Save changes',cancel:'Cancel',signOut:'Sign out'}});
  const canonicalJson=value=>JSON.stringify(value&&typeof value==='object'?(function sort(v){if(Array.isArray(v))return v.map(sort);if(v&&typeof v==='object')return Object.fromEntries(Object.keys(v).sort().map(k=>[k,sort(v[k])]));return v})(value):value);
  const uniqueIds=list=>Array.isArray(list)&&new Set(list.map(x=>x?.id)).size===list.length&&list.every(x=>x&&typeof x.id==='string'&&x.id);
  function normalizeAccess(user){
    if(!user?.active)return freeze({version:2,grants:{}});if(user.role==='Admin')return freeze({version:2,grants:Object.fromEntries(CEILINGS.Admin.map(id=>[id,'enabled']))});
    if(user.access?.version!==2||!user.access.grants||typeof user.access.grants!=='object'||Array.isArray(user.access.grants))return freeze({version:2,grants:{}});
    const ceiling=new Set(CEILINGS[user.role]||[]),grants={},defaults=LEGACY_DEFAULTS[user.role]||[];for(const [id,value] of Object.entries(user.access.grants))if(ceiling.has(id)&&['enabled','disabled'].includes(value))grants[id]=value;
    for(const id of defaults)if(!(id in grants)&&ceiling.has(id))grants[id]='enabled';
    if(grants['section.tools']!=='enabled')for(const id of ['section.suppliers','section.specs'])if(grants[id]==='enabled')grants[id]='disabled';return freeze({version:2,grants});
  }
  const hasPermission=(user,id)=>normalizeAccess(user).grants[id]==='enabled';
  function validateState(state){
    const errors=[];if(!state||typeof state!=='object')return {ok:false,errors:['state.type']};if(JSON.stringify(state.schemaVersions)!==JSON.stringify(VERSION))errors.push('schema.version');if(!Number.isInteger(state.meta?.storeRevision)||state.meta.storeRevision<0)errors.push('meta.storeRevision');
    for(const name of ['users','projects','orders','suppliers','specs','tasks'])if(!uniqueIds(state[name]))errors.push(`${name}.ids`);for(const name of ['projectMemberships','projectCompanies','supplierProjectLinks','clientProjectLinks','clientOrderAuthorizations','quarantine'])if(!Array.isArray(state[name]))errors.push(`${name}.type`);if(errors.length)return {ok:false,errors};
    const users=new Map(state.users.map(x=>[x.id,x])),projects=new Map(state.projects.map(x=>[x.id,x])),orders=new Map(state.orders.map(x=>[x.id,x])),suppliers=new Map(state.suppliers.map(x=>[x.id,x]));
    state.users.forEach(user=>{if(!['Admin','Worker','Client'].includes(user.role))errors.push(`user.role:${user.id}`);if(typeof user.active!=='boolean')errors.push(`user.active:${user.id}`);if(user.role!=='Admin'&&(user.access?.version!==2||!user.access.grants||Array.isArray(user.access.grants)))errors.push(`user.access:${user.id}`)});
    if(state.users.filter(x=>x.role==='Admin'&&x.active).length<1)errors.push('admin.active');state.orders.forEach(x=>{if(!projects.has(x.projectId))errors.push(`order.project:${x.id}`)});state.specs.forEach(x=>{if(typeof x.projectId!=='string'||!projects.has(x.projectId))errors.push(`spec.project:${x.id}`)});state.tasks.forEach(x=>{if(!users.has(x.assignee))errors.push(`task.assignee:${x.id}`)});
    const pair=(name,a,b,valid)=>{const seen=new Set;state[name].forEach(x=>{let key=`${x[a]}|${x[b]}`;if(seen.has(key))errors.push(`${name}.duplicate:${key}`);seen.add(key);if(!valid(x))errors.push(`${name}.foreign:${key}`)})};pair('projectMemberships','userId','projectId',x=>users.get(x.userId)?.role==='Worker'&&projects.has(x.projectId));pair('projectCompanies','projectId','companyId',x=>projects.has(x.projectId)&&typeof x.companyId==='string'&&x.companyId);pair('supplierProjectLinks','supplierId','projectId',x=>suppliers.has(x.supplierId)&&projects.has(x.projectId));
    const company=pid=>state.projectCompanies.filter(x=>x.projectId===pid),clientTuples=new Set;state.clientProjectLinks.forEach(x=>{let key=`${x.clientId}|${x.companyId}|${x.projectId}`;if(clientTuples.has(key))errors.push(`clientProjectLinks.duplicate:${key}`);clientTuples.add(key);if(users.get(x.clientId)?.role!=='Client'||!projects.has(x.projectId)||company(x.projectId).length!==1||company(x.projectId)[0].companyId!==x.companyId)errors.push(`clientProjectLinks.foreign:${key}`)});
    const auth=new Set;state.clientOrderAuthorizations.forEach(x=>{let key=`${x.clientId}|${x.orderId}`;if(auth.has(key))errors.push(`clientOrderAuthorizations.duplicate:${key}`);auth.add(key);let order=orders.get(x.orderId);if(!order||order.projectId!==x.projectId||!clientTuples.has(`${x.clientId}|${x.companyId}|${x.projectId}`)||company(x.projectId).length!==1||company(x.projectId)[0].companyId!==x.companyId)errors.push(`clientOrderAuthorizations.foreign:${key}`)});return {ok:!errors.length,errors};
  }
  function migrateState(input){
    if(!input||typeof input!=='object')return {ok:false,state:null,migrated:false,errors:['state.type'],quarantine:[]};if(input.schemaVersions){if(JSON.stringify(input.schemaVersions)!==JSON.stringify(VERSION))return {ok:false,state:null,migrated:false,errors:['schema.version'],quarantine:[]};let state=clone(input),v=validateState(state);return {ok:v.ok,state:v.ok?state:null,migrated:false,from:VERSION,to:VERSION,errors:v.errors,quarantine:clone(state.quarantine||[])}}
    const state=clone(input),quarantine=[];for(const name of ['projectMemberships','projectCompanies','supplierProjectLinks','clientLinks','clientProjectLinks','clientOrderAuthorizations'])if(Array.isArray(state[name])&&state[name].length){quarantine.push({kind:name,records:clone(state[name])});state[name]=[]}
    state.schemaVersions=clone(VERSION);state.meta={storeRevision:0};for(const name of ['users','projects','orders','suppliers','specs','tasks'])state[name]=Array.isArray(state[name])?state[name]:[];state.projectMemberships=[];state.projectCompanies=[];state.supplierProjectLinks=[];state.clientProjectLinks=[];state.clientOrderAuthorizations=[];state.quarantine=quarantine;
    state.users.forEach(user=>{if(user.role==='Admin')delete user.access;else if(!user.access)user.access={version:2,grants:Object.fromEntries((LEGACY_DEFAULTS[user.role]||[]).map(id=>[id,'enabled']))};else if(user.access.version!==2)user.access={version:2,grants:{}};if(user.access&&user.access.version===2&&user.access.grants){let defaults=LEGACY_DEFAULTS[user.role]||[];for(let id of defaults)if(!(id in user.access.grants))user.access.grants[id]='enabled'}});let v=validateState(state);return {ok:v.ok,state:v.ok?state:null,migrated:true,from:null,to:VERSION,errors:v.errors,quarantine};
  }
  const memberships=(state,user)=>new Set(state.projectMemberships.filter(x=>x.userId===user.id).map(x=>x.projectId));
  const allProjects=user=>user?.access?.projectScope?.mode==='all';
  function canReadClientOrder(state,user,orderId){if(!validateState(state).ok||!user?.active)return false;const order=state.orders.find(x=>x.id===orderId);if(!order)return false;if(user.role==='Admin')return true;if(user.role!=='Client')return false;return state.clientProjectLinks.some(x=>x.clientId===user.id&&x.projectId===order.projectId)}
  function selectProjectsForActor(state,user){if(!validateState(state).ok||!user?.active)return [];if(user.role==='Admin'||(user.role==='Worker'&&allProjects(user)))return clone(state.projects);if(user.role==='Worker'){let own=memberships(state,user);return clone(state.projects.filter(x=>own.has(x.id)))}return []}
  function supplierScope(state,user,id){if(user.role==='Admin'||allProjects(user))return 'own';if(user.role!=='Worker')return 'foreign';let own=memberships(state,user),links=state.supplierProjectLinks.filter(x=>x.supplierId===id);if(!links.length)return 'foreign';let count=links.filter(x=>own.has(x.projectId)).length;return count===links.length?'own':count?'mixed':'foreign'}
  function selectSuppliersForActor(state,user){if(!validateState(state).ok||!user?.active)return [];if(user.role==='Admin')return clone(state.suppliers);return state.suppliers.filter(x=>supplierScope(state,user,x.id)!=='foreign').map(x=>({...clone(x),scope:supplierScope(state,user,x.id)}))}
  function selectSpecsForActor(state,user){if(!validateState(state).ok||!user?.active)return [];if(user.role==='Admin'||allProjects(user))return clone(state.specs);let own=memberships(state,user);return clone(state.specs.filter(x=>own.has(x.projectId)))}
  function selectOrdersForActor(state,user){if(!validateState(state).ok||!user?.active)return [];if(user.role==='Admin')return clone(state.orders);return user.role==='Client'?clone(state.orders.filter(x=>canReadClientOrder(state,user,x.id))):[]}
  function selectTasksForActor(state,user){if(!validateState(state).ok||!user?.active)return [];return clone(user.role==='Admin'?state.tasks:user.role==='Worker'?state.tasks.filter(x=>x.assignee===user.id):[])}
  function authorizeRoute({state,user,route,projectId}){if(!validateState(state).ok)return decision(false,'state.invalid');if(!user?.active)return decision(false,'actor.inactive');if(route==='settings')return decision(user.role==='Admin',user.role==='Admin'?'allowed':'route.denied');if(route==='project'){if(user.role==='Client'||!hasPermission(user,'section.dashboard'))return decision(false,'route.denied');return decision(selectProjectsForActor(state,user).some(x=>x.id===projectId),'scope.project')}let permission=ROUTES[route];if(!permission)return decision(false,'route.unknown');return decision(hasPermission(user,permission),hasPermission(user,permission)?'allowed':'permission.denied')}
  const resolve=(state,name,id)=>name&&RESOLVERS[name]?state[RESOLVERS[name]].find(x=>x.id===id)||null:null;
  function authorizeAction({state,user,action,phase,route,targetId,selectedProjectId,recovery=false,signedOut=false}){const p=ACTION_POLICY[action];if(!p)return decision(false,'action.unknown');if(!['execute','open','commit','async-commit'].includes(phase))return decision(false,'phase.unknown');if(!p.phases.includes(phase))return decision(false,'phase.denied');let role=recovery?'recovery':signedOut?'signed_out':user?.role;if(!p.roles.includes(role))return decision(false,'role.denied');if(!p.routes.includes('*')&&!p.routes.includes(route))return decision(false,'route.context');if(p.target==='required'&&!targetId)return decision(false,'target.required');if(p.target==='forbidden'&&targetId)return decision(false,'target.forbidden');if(!recovery&&!signedOut){if(!validateState(state).ok)return decision(false,'state.invalid');if(!user?.active)return decision(false,'actor.inactive');if(p.permission&&!hasPermission(user,p.permission))return decision(false,'permission.denied')}let resource=resolve(state,p.resolver,targetId);if(p.resolver&&!resource)return decision(false,'resource.missing');if(p.scope==='own-task'&&resource.assignee!==user.id)return decision(false,'scope.task');if(['project-read','project-write'].includes(p.scope)){let pid=resource?.id||selectedProjectId;if(!pid||!selectProjectsForActor(state,user).some(x=>x.id===pid))return decision(false,'scope.project')}if(p.scope==='order-project-write'&&!selectProjectsForActor(state,user).some(x=>x.id===resource?.projectId))return decision(false,'scope.project');if(p.scope==='supplier-own'&&supplierScope(state,user,targetId)!=='own')return decision(false,'scope.supplier');if(p.scope==='spec-own'&&!selectSpecsForActor(state,user).some(x=>x.id===targetId))return decision(false,'scope.spec');if(p.scope==='client-order'&&!canReadClientOrder(state,user,targetId))return decision(false,'scope.client-order');return decision(true,'allowed')}
  function createAccessDraft(user,storeRevision=0,scopes={}){let access=normalizeAccess(user||{role:'Worker',active:true,access:{version:2,grants:{}}});return freeze({draftId:`draft-${user?.id||'new'}`,baseStoreRevision:storeRevision,revision:0,confirmedRevision:-1,role:user?.role||'Worker',grants:clone(access.grants),projectMode:scopes.projectMode||user?.access?.projectScope?.mode||'selected',projectIds:clone(scopes.projectIds||[]),clientProjectIds:clone(scopes.clientProjectIds||[]),clientOrderIds:clone(scopes.clientOrderIds||[]),pendingDecision:null})}
  function reduceAccessDraft(input,event){let d=clone(input),bump=fn=>{fn();d.revision++;d.confirmedRevision=-1};if(event.type==='confirm')d.confirmedRevision=d.revision;else if(event.type==='grant')bump(()=>{if(event.value==='none')delete d.grants[event.id];else d.grants[event.id]=event.value});else if(event.type==='project-mode')bump(()=>d.projectMode=event.value==='all'?'all':'selected');else if(['identity','worker-project','client-project','client-order'].includes(event.type))bump(()=>d[event.key||event.type]=event.value);else if(event.type==='request-role')d.pendingDecision={type:'role',value:event.role};else if(event.type==='cancel-role')d.pendingDecision=null;else if(event.type==='confirm-role'&&d.pendingDecision?.type==='role')bump(()=>{d.role=d.pendingDecision.value;d.grants={};d.projectMode='selected';d.projectIds=[];d.clientProjectIds=[];d.clientOrderIds=[];d.pendingDecision=null});else if(event.type==='request-tools-remove')d.pendingDecision={type:'tools'};else if(event.type==='cancel-tools-remove')d.pendingDecision=null;else if(event.type==='confirm-tools-remove'&&d.pendingDecision?.type==='tools')bump(()=>{delete d.grants['section.tools'];delete d.grants['section.suppliers'];delete d.grants['section.specs'];d.pendingDecision=null});return freeze(d)}
  return freeze({VERSION,SECTIONS,CEILINGS,LEGACY_DEFAULTS,I18N,canonicalJson,normalizeAccess,hasPermission,validateState,migrateState,selectProjectsForActor,selectSuppliersForActor,selectSpecsForActor,selectOrdersForActor,selectTasksForActor,canReadClientOrder,authorizeRoute,authorizeAction,createAccessDraft,reduceAccessDraft,listKnownActions:()=>Object.freeze(Object.keys(ACTION_POLICY).slice().sort()),t:(lang,key)=>I18N[lang]?.[key]||''});
});
