const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');

const prototypeDir=__dirname;
const outputDir=path.join(__dirname,'..','tmp','spreadsheets','generated');
fs.mkdirSync(outputDir,{recursive:true});

const downloads=[];
const links=[];
const context={
  window:{},TextEncoder,Uint8Array,Intl,Date,Blob,
  console,
  setTimeout:fn=>{fn();return 1},
  URL:{
    createObjectURL(blob){downloads.push(blob);return `blob:test-${downloads.length}`},
    revokeObjectURL(){}
  },
  document:{
    body:{append(){}},
    createElement(){const link={href:'',download:'',click(){links.push(this.download)},remove(){}};return link;}
  },
  fetch:async resource=>{
    const filePath=path.join(prototypeDir,String(resource).replaceAll('/',path.sep));
    const bytes=fs.readFileSync(filePath);
    return {ok:true,text:async()=>bytes.toString('utf8'),arrayBuffer:async()=>bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength)};
  }
};
vm.createContext(context);
vm.runInContext(fs.readFileSync(path.join(prototypeDir,'reports.js'),'utf8'),context,{filename:'reports.js'});

function unzipStored(bytes){
  const view=Buffer.from(bytes),entries=new Map();let offset=0;
  while(offset+30<=view.length&&view.readUInt32LE(offset)===0x04034b50){
    const size=view.readUInt32LE(offset+18),nameLength=view.readUInt16LE(offset+26),extraLength=view.readUInt16LE(offset+28),nameStart=offset+30,dataStart=nameStart+nameLength+extraLength,name=view.subarray(nameStart,nameStart+nameLength).toString('utf8');
    entries.set(name,view.subarray(dataStart,dataStart+size));offset=dataStart+size;
  }
  return entries;
}

(async()=>{
  const project={id:'p1',code:'PRJ-041',name:'Hotel Costa Azul',areas:'9',warehouse:'Warehouse Lima',city:'Lima',country:'Peru',invoices:[
    {id:'i1',status:'issued',type:'FF&E',poNumber:'PRJ-041-0001',number:'PR-2026-00001',invoiceNumber:'INV-001',invoiceDate:'2026-09-10',requestDate:'2026-09-11',invoiceTotal:'1500',currency:'USD',paymentEvidence:'OP-101',paymentAmount:'1500',transferDate:'2026-09-11',requestDetail:'First payment'},
    {id:'i2',status:'cancelled',type:'OS&E',poNumber:'PRJ-041-8001',number:'PR-2026-00002',invoiceNumber:'INV-002',invoiceDate:'2026-09-09',requestDate:'2026-09-10',invoiceTotal:'500',currency:'PEN'},
    {id:'i3',status:'draft',poNumber:'PRJ-041-DRAFT',number:'DRAFT',invoiceTotal:'999',currency:'USD'}
  ]};
  const orders=[
    {id:'o1',projectId:'p1',status:'approved',number:'PRJ-041-0001',manufacturer:'Maker A',source:'Source A',amount:'$ 2,000.00',date:'04/09/2026',items:[{reference:'CHA-01',description:'Chair',quantity:2,unit:'ea',currency:'USD',unitCost:750},{reference:'TBL-01',description:'Table',quantity:1,unit:'ea',currency:'USD',unitCost:500}]},
    {id:'o2',projectId:'p1',status:'cancelled',number:'PRJ-041-8001',supplier:'Supplier B',amount:'S/ 500.00',date:'05/09/2026',voidedAt:'2026-09-10T17:10:00Z',items:[{reference:'GLS-01',description:'Glassware',quantity:10,unit:'set',currency:'PEN',unitCost:50}]},
    {id:'o3',projectId:'p1',status:'pending',number:'PRJ-041-DRAFT',amount:'$ 999.00',items:[{description:'Draft item',quantity:1,unitCost:999}]},
    {id:'o4',projectId:'p2',status:'approved',number:'OTHER-0001',amount:'$ 100.00',items:[{description:'Other project',quantity:1,unitCost:100}]}
  ];

  const poResult=await context.window.VAAKReports.purchaseOrders(project,orders);
  const poBytes=Buffer.from(await downloads[0].arrayBuffer());
  fs.writeFileSync(path.join(outputDir,'generated-po-item-listing.xlsx'),poBytes);
  const poEntries=unzipStored(poBytes),poSheet=poEntries.get('xl/worksheets/sheet1.xml').toString('utf8');
  assert.equal(poResult.rows,3);
  assert.equal(poResult.orders,2);
  assert.match(poSheet,/PRJ-041-0001/);
  assert.match(poSheet,/PRJ-041-8001/);
  assert.doesNotMatch(poSheet,/PRJ-041-DRAFT/);
  assert.match(poSheet,/autoFilter ref="A7:T10"/);
  assert.match(poSheet,/mergeCell ref="A13:T13"/);
  assert.match(poSheet,/REPORT GENERATED BY VAAK/);
  assert.doesNotMatch(poSheet,/REPORTE GENERADO/);
  assert.equal(Buffer.compare(poEntries.get('xl/media/image1.png'),fs.readFileSync(path.join(prototypeDir,'assets','reports','hpg-report-logo.png'))),0);

  const invoiceResult=await context.window.VAAKReports.invoices(project,orders);
  const invoiceBytes=Buffer.from(await downloads[1].arrayBuffer());
  fs.writeFileSync(path.join(outputDir,'generated-invoice-details.xlsx'),invoiceBytes);
  const invoiceEntries=unzipStored(invoiceBytes),invoiceSheet=invoiceEntries.get('xl/worksheets/sheet1.xml').toString('utf8');
  assert.equal(invoiceResult.rows,2);
  assert.equal(invoiceResult.invoices,2);
  assert.match(invoiceSheet,/INV-001/);
  assert.match(invoiceSheet,/INV-002/);
  assert.doesNotMatch(invoiceSheet,/PRJ-041-DRAFT/);
  assert.match(invoiceSheet,/autoFilter ref="A7:R9"/);
  assert.match(invoiceSheet,/mergeCell ref="A12:R12"/);
  assert.match(invoiceSheet,/>TYPE</);
  assert.match(invoiceSheet,/INVOICED USD/);
  assert.doesNotMatch(invoiceSheet,/>TIPO</);
  assert.deepEqual(links,[
    'VAAK_Reporte PO Item Listing_Hotel_Costa_Azul.xlsx',
    'VAAK_Reporte Invoice Details_Hotel_Costa_Azul.xlsx'
  ]);
  console.log('reports.test.js: OK');
})().catch(error=>{console.error(error);process.exitCode=1});
