/* Generador XLSX local sin dependencias: conserva el formato ejecutivo HPG de los reportes de referencia. */
(() => {
  const enc = new TextEncoder();
  const escapeXml = value => String(value ?? '').replace(/[&<>"']/g, char => ({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;' }[char]));
  const col = index => { let result=''; for(index++; index; index=Math.floor((index-1)/26)) result=String.fromCharCode(65+(index-1)%26)+result; return result; };
  const crcTable = (() => { const table=[]; for(let i=0;i<256;i++){let value=i;for(let bit=0;bit<8;bit++) value=value&1 ? 0xedb88320^(value>>>1) : value>>>1;table[i]=value>>>0;} return table; })();
  const crc32 = bytes => { let value=0xffffffff; for(const byte of bytes) value=crcTable[(value^byte)&255]^(value>>>8); return (value^0xffffffff)>>>0; };
  const u16 = value => new Uint8Array([value&255,(value>>>8)&255]);
  const u32 = value => new Uint8Array([value&255,(value>>>8)&255,(value>>>16)&255,(value>>>24)&255]);
  const concat = parts => { const length=parts.reduce((total,part)=>total+part.length,0),result=new Uint8Array(length);let offset=0;for(const part of parts){result.set(part,offset);offset+=part.length;}return result; };
  const zip = files => { let offset=0,local=[],central=[]; for(const [name,content] of files){const nameBytes=enc.encode(name),bytes=typeof content==='string'?enc.encode(content):content,crc=crc32(bytes);local.push(concat([u32(0x04034b50),u16(20),u16(0),u16(0),u16(0),u16(0),u32(crc),u32(bytes.length),u32(bytes.length),u16(nameBytes.length),u16(0),nameBytes,bytes]));central.push(concat([u32(0x02014b50),u16(20),u16(20),u16(0),u16(0),u16(0),u16(0),u32(crc),u32(bytes.length),u32(bytes.length),u16(nameBytes.length),u16(0),u16(0),u16(0),u16(0),u32(0),u32(offset),nameBytes]));offset+=local.at(-1).length;}const body=concat(local),directory=concat(central);return concat([body,directory,u32(0x06054b50),u16(0),u16(0),u16(files.length),u16(files.length),u32(directory.length),u32(body.length),u16(0)]); };
  const styles = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><numFmts count="1"><numFmt numFmtId="164" formatCode="#,##0.00"/></numFmts><fonts count="3"><font><sz val="10"/><color rgb="FF5A4638"/><name val="Arial"/></font><font><b/><sz val="10"/><color rgb="FFFFFFFF"/><name val="Arial"/></font><font><b/><sz val="18"/><color rgb="FF5A4638"/><name val="Arial"/></font></fonts><fills count="6"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF604432"/><bgColor indexed="64"/></patternFill></fill><fill><patternFill patternType="solid"><fgColor rgb="FFF5F1EA"/><bgColor indexed="64"/></patternFill></fill><fill><patternFill patternType="solid"><fgColor rgb="FFF3F0E9"/><bgColor indexed="64"/></patternFill></fill><fill><patternFill patternType="solid"><fgColor rgb="FFE6F0E7"/><bgColor indexed="64"/></patternFill></fill></fills><borders count="2"><border><left/><right/><top/><bottom/><diagonal/></border><border><left style="thin"><color rgb="FFE8E1D9"/></left><right style="thin"><color rgb="FFE8E1D9"/></right><top style="thin"><color rgb="FFE8E1D9"/></top><bottom style="thin"><color rgb="FFE8E1D9"/></bottom><diagonal/></border></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="9"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/><xf numFmtId="0" fontId="2" fillId="0" borderId="0" applyFont="1"/><xf numFmtId="0" fontId="0" fillId="0" borderId="0" applyFont="1"><alignment horizontal="left"/></xf><xf numFmtId="0" fontId="0" fillId="4" borderId="0" applyFill="1"><alignment horizontal="center"/></xf><xf numFmtId="0" fontId="2" fillId="4" borderId="0" applyFill="1"><alignment horizontal="center"/></xf><xf numFmtId="0" fontId="1" fillId="2" borderId="0" applyFont="1" applyFill="1"><alignment horizontal="center" vertical="center" wrapText="1"/></xf><xf numFmtId="0" fontId="0" fillId="3" borderId="1" applyFill="1" applyBorder="1"/><xf numFmtId="164" fontId="0" fillId="3" borderId="1" applyFill="1" applyBorder="1"><alignment horizontal="right"/></xf><xf numFmtId="0" fontId="0" fillId="5" borderId="1" applyFill="1" applyBorder="1"><alignment horizontal="center"/></xf></cellXfs></styleSheet>`;
  const cell = (row,column,value,style=6,number=false) => value===null||value===undefined||value==='' ? '' : `<c r="${col(column)}${row}" s="${style}"${number?'' : ' t="inlineStr"'}>${number?`<v>${Number(value)||0}</v>`:`<is><t>${escapeXml(value)}</t></is>`}</c>`;
  const sheet = ({title,project,metrics,headers,rows,widths}) => { const data=[]; data.push(`<row r="1" ht="29" customHeight="1">${cell(1,3,title,1)}</row>`);data.push(`<row r="2" ht="20" customHeight="1">${cell(2,3,project.name,2)}</row>`);data.push(`<row r="3" ht="18" customHeight="1">${cell(3,3,'HPG INTERNATIONAL LATINOAMERICANA SAC · REPORTE GENERADO POR VAAK',2)}</row>`);let metricCells=[];metrics.forEach((metric,index)=>{let start=5+index*3;metricCells.push(cell(4,start,metric.label,3),cell(5,start,metric.value,4,metric.number));});data.push(`<row r="4" ht="18" customHeight="1">${metricCells.filter((_,i)=>i%2===0).join('')}</row>`);data.push(`<row r="5" ht="24" customHeight="1">${metricCells.filter((_,i)=>i%2).join('')}</row>`);data.push('<row r="6" ht="10" customHeight="1"/>');data.push(`<row r="7" ht="34" customHeight="1">${headers.map((header,index)=>cell(7,index,header,5)).join('')}</row>`);rows.forEach((record,index)=>data.push(`<row r="${index+8}" ht="20" customHeight="1">${record.map((value,column)=>cell(index+8,column,value.value??value,value.style??(column===headers.length-1?8:(value.number?7:6)),value.number)).join('')}</row>`));const last=Math.max(8,rows.length+7),columns=widths.map((width,index)=>`<col min="${index+1}" max="${index+1}" width="${width}" customWidth="1"/>`).join('');return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetViews><sheetView workbookViewId="0" showGridLines="0"><pane ySplit="7" topLeftCell="A8" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><sheetFormatPr defaultRowHeight="15"/><cols>${columns}</cols><sheetData>${data.join('')}</sheetData><mergeCells count="3"><mergeCell ref="D1:H1"/><mergeCell ref="D2:H2"/><mergeCell ref="D3:H3"/></mergeCells><autoFilter ref="A7:${col(headers.length-1)}${last}"/></worksheet>`; };
  const packageFile = (name,xml) => zip([
    ['[Content_Types].xml','<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/></Types>'],
    ['_rels/.rels','<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>'],
    ['xl/workbook.xml',`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="${escapeXml(name)}" sheetId="1" r:id="rId1"/></sheets></workbook>`],
    ['xl/_rels/workbook.xml.rels','<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>'],
    ['xl/styles.xml',styles],['xl/worksheets/sheet1.xml',xml]
  ]);
  const amount = value => Number(String(value ?? '').replace(/[^0-9.-]/g,'')) || 0;
  const currency = value => String(value ?? '').includes('$') ? 'USD' : String(value ?? '').includes('€') ? 'EUR' : 'PEN';
  const download = (name,bytes) => { const url=URL.createObjectURL(new Blob([bytes],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'})),link=document.createElement('a');link.href=url;link.download=name;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1500); };
  const purchaseOrders = (project,orders) => { const selected=orders.filter(order=>order.projectId===project.id),records=selected.flatMap(order=>(order.items?.length?order.items:[{}]).map((item,index)=>[{value:order.number},{value:`${order.number}-${String(index+1).padStart(3,'0')}`,style:8},{value:item.description||'—'},{value:order.manufacturer||order.supplier||'—'},{value:item.quantity||1,number:true},{value:item.unit||'ea'},{value:item.currency||currency(order.amount)},{value:item.unitCost||amount(order.amount),number:true},{value:(item.quantity||1)*(item.unitCost||amount(order.amount)),number:true},{value:order.deliveryDate||'—'},{value:order.shipDate||'—'},{value:order.receivedDate||'—'},{value:order.deliveredDate||'—'},{value:order.installedDate||'—'},{value:order.trackingStatus||order.status||'Emitida',style:8},{value:order.trackingUpdatedAt||order.date||'—'},{value:order.currentLocation||'—'},{value:order.leadTime||'—'},{value:project.areas||'—'},{value:order.area||'—'}]));const totals=selected.reduce((all,order)=>{all[currency(order.amount)]=(all[currency(order.amount)]||0)+amount(order.amount);return all;},{});const xml=sheet({title:'PO Item Listing',project,metrics:[{label:'LINE ITEMS',value:records.length,number:true},{label:'SUBMITTED',value:selected.length,number:true},{label:'PO CONFIRMED',value:selected.filter(order=>order.trackingStatus==='Delivered').length,number:true},{label:'EXT. COST PEN',value:totals.PEN||0,number:true},{label:'EXT. COST USD',value:totals.USD||0,number:true},{label:'EXT. COST EUR',value:totals.EUR||0,number:true}],headers:['PO NUM','ITEM #','ITEM DESCRIPTION','MANUFACTURER | SOURCE','QTY','UM','CUR','UN COST','EXT COST','EST DELIVERY','ACTUAL SHIP DT','RECEIVED','DELIVERED FINAL','INSTALLED','STATUS','STATUS DT','CURR LOC','LEAD TIME','AREAS','PO AREA'],rows:records,widths:[16,15,34,31,8,8,8,15,16,15,16,14,16,13,15,14,14,13,14,15]});download(`VAAK_Reporte_PO_Item_Listing_${project.name.replace(/[^a-z0-9]+/gi,'_')}.xlsx`,packageFile('PO Item Listing',xml)); };
  const invoices = (project,orders) => { const selected=project.invoices||[],findOrder=invoice=>orders.find(order=>order.projectId===project.id&&(order.number===invoice.poNumber||order.id===invoice.orderId));const records=selected.map(invoice=>{const order=findOrder(invoice),curr=invoice.invoiceCurrency||invoice.currency||currency(order?.amount);return [{value:invoice.type||'FF&E',style:8},{value:invoice.poNumber||order?.number||'—'},{value:order?.date||'—'},{value:invoice.sourceManufacturer||order?.supplier||'—'},{value:amount(order?.amount),number:true},{value:invoice.invoiceNumber||'—',style:8},{value:invoice.invoiceDate||'—'},{value:amount(invoice.invoiceTotal||invoice.totalRequest),number:true},{value:curr},{value:invoice.requestDate||'—'},{value:invoice.number||'—',style:8},{value:invoice.paymentEvidence||'—'},{value:amount(invoice.paymentAmount),number:true},{value:invoice.approvalDate||'—'},{value:invoice.invoiceNote||'—'},{value:invoice.requestDetail||'—'},{value:invoice.deliveryLocation||project.warehouse||'—'},{value:invoice.destination||'—'}]});const totals=selected.reduce((all,invoice)=>{let curr=invoice.invoiceCurrency||invoice.currency||'PEN';all[curr]=(all[curr]||0)+amount(invoice.invoiceTotal||invoice.totalRequest);return all;},{});const xml=sheet({title:'Invoice Details',project,metrics:[{label:'INVOICES',value:selected.length,number:true},{label:'PAYMENT REQ.',value:selected.length,number:true},{label:'FACTURADO PEN',value:totals.PEN||0,number:true},{label:'FACTURADO USD',value:totals.USD||0,number:true},{label:'FACTURADO EUR',value:totals.EUR||0,number:true}],headers:['TIPO','PO NUMBER','FECHA PO','MANUFACTURER','VALOR TOTAL ORDEN','INVOICE #','INV. DATE','INV. AMOUNT','CUR','FECHA PR','PR NUMBER','EVIDENCIA DE PAGO','MONTO PAGADO','FECHA TRANS.','INVOICE NOTE','COMENTARIOS HPG','LUGAR DE ENTREGA','DESTINO'],rows:records,widths:[11,17,14,30,18,16,14,16,8,14,17,20,16,15,18,28,21,18]});download(`VAAK_Reporte_Invoice_Details_${project.name.replace(/[^a-z0-9]+/gi,'_')}.xlsx`,packageFile('Invoice Details',xml)); };
  window.VAAKReports={purchaseOrders,invoices};
})();
